parameters:
  configurationName: ''
  configurationParameters: ''
  xdebugConfigurationParameters: '--with-xdebug-compression'

jobs:
  - job: ${{ parameters.configurationName }}
    pool:
      vmImage: 'macOS-10.15'
    steps:
    - template: brew.yml
    - template: php.yml
      parameters:
        phpVersion: ${{ parameters.phpVersion }}
        configurationParameters: ${{ parameters.configurationParameters }}
    - script: |
        export PATH="/usr/local/bin:$PATH"
        phpize && ./configure ${{ parameters.xdebugConfigurationParameters }} && make clean && make all && sudo make install
      displayName: 'Compile Xdebug'
    - template: test.yml
      parameters:
        configurationName: ${{ parameters.configurationName }}
    - template: test.yml
      parameters:
        configurationName: ${{ parameters.configurationName }}
        runTestsName: 'Opcache'
        opCache: 'yes'
