<?php
foreach ($foo as $k => $v) {
    switch ($v) {
		case 1: echo "foo {$v}\n"; break;
		case 2: echo "foo {$v}\n"; break;
		case 3: echo "foo {$v}\n"; break;
		case 4: echo "foo {$v}\n"; break;
		case 5: echo "foo {$v}\n"; break;
		case 6: echo "foo {$v}\n"; break;
		case 7: echo "foo {$v}\n"; break;
		case 8: echo "foo {$v}\n"; break;
		case 9: echo "foo {$v}\n"; break;
		case 10: echo "foo {$v}\n"; break;
		case 11: echo "foo {$v}\n"; break;
		case 12: echo "foo {$v}\n"; break;
		case 13: echo "foo {$v}\n"; break;
		case 14: echo "foo {$v}\n"; break;
		case 15: echo "foo {$v}\n"; break;
		case 16: echo "foo {$v}\n"; break;
		case 17: echo "foo {$v}\n"; break;
		case 18: echo "foo {$v}\n"; break;
		case 19: echo "foo {$v}\n"; break;
		case 20: echo "foo {$v}\n"; break;
		case 21: echo "foo {$v}\n"; break;
		case 22: echo "foo {$v}\n"; break;
		case 23: echo "foo {$v}\n"; break;
		case 24: echo "foo {$v}\n"; break;
		case 25: echo "foo {$v}\n"; break;
		case 26: echo "foo {$v}\n"; break;
		case 27: echo "foo {$v}\n"; break;
		case 28: echo "foo {$v}\n"; break;
		case 29: echo "foo {$v}\n"; break;
		case 30: echo "foo {$v}\n"; break;
		case 31: echo "foo {$v}\n"; break;
		case 32: echo "foo {$v}\n"; break;
		case 33: echo "foo {$v}\n"; break;
		case 34: echo "foo {$v}\n"; break;
		case 35: echo "foo {$v}\n"; break;
		case 36: echo "foo {$v}\n"; break;
		case 37: echo "foo {$v}\n"; break;
		case 38: echo "foo {$v}\n"; break;
		case 39: echo "foo {$v}\n"; break;
		case 40: echo "foo {$v}\n"; break;
    }
}
